name: Generate Sitemap

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "17 3 * * 1"
  workflow_dispatch:

# Prevent overlapping runs from racing the push
concurrency:
  group: sitemap-update
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://www.shunyapublications.com
          # path-to-root: docs   # uncomment ONLY if your site is served from /docs

      - name: Commit & push sitemap (rebase-safe)
        run: |
          set -euo pipefail
          if [ ! -f sitemap.xml ]; then
            echo "sitemap.xml not found"
            exit 0
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # make sure we're up-to-date before committing
          git fetch origin main
          git checkout main
          git pull --rebase origin main

          git add sitemap.xml
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Automated sitemap update"
          git push origin HEAD:main

      # ---- OPTIONAL: IndexNow (use a real key or skip) ----
      - name: Notify Bing via IndexNow (optional)
        if: ${{ secrets.INDEXNOW_KEY != '' }}
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
        run: |
          cat > urls.txt <<'EOF'
          https://www.shunyapublications.com/
          https://www.shunyapublications.com/books.html
          https://www.shunyapublications.com/journal.html
          https://www.shunyapublications.com/ipaas.html
          https://www.shunyapublications.com/memory-journals.html
          EOF

          python - << 'PY'
          import json, os
          key = os.environ.get("INDEXNOW_KEY","").strip()
          if not key:
              raise SystemExit(0)
          host = "www.shunyapublications.com"
          keyLocation = f"https://{host}/indexnow-{key}.txt"
          with open("urls.txt","r",encoding="utf-8") as f:
              urls = [u.strip() for u in f if u.strip()]
          payload = {"host":host, "key":key, "keyLocation":keyLocation, "urlList":urls}
          with open("payload.json","w",encoding="utf-8") as f:
              json.dump(payload, f, ensure_ascii=False)
          PY

          curl -sS -H "Content-Type: application/json; charset=utf-8" \
               -d @payload.json https://www.bing.com/indexnow || true
